<?php

namespace DahouetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommissaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommissaireRepository extends EntityRepository
{
}
