<?php

namespace DahouetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParticipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipeRepository extends EntityRepository
{
}
