<?php

namespace Proxies\__CG__\DahouetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Classe extends \DahouetBundle\Entity\Classe implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'DahouetBundle\\Entity\\Classe' . "\0" . 'numclas', '' . "\0" . 'DahouetBundle\\Entity\\Classe' . "\0" . 'libclas', '' . "\0" . 'DahouetBundle\\Entity\\Classe' . "\0" . 'coefclas', '' . "\0" . 'DahouetBundle\\Entity\\Classe' . "\0" . 'jauge', '' . "\0" . 'DahouetBundle\\Entity\\Classe' . "\0" . 'codser');
        }

        return array('__isInitialized__', '' . "\0" . 'DahouetBundle\\Entity\\Classe' . "\0" . 'numclas', '' . "\0" . 'DahouetBundle\\Entity\\Classe' . "\0" . 'libclas', '' . "\0" . 'DahouetBundle\\Entity\\Classe' . "\0" . 'coefclas', '' . "\0" . 'DahouetBundle\\Entity\\Classe' . "\0" . 'jauge', '' . "\0" . 'DahouetBundle\\Entity\\Classe' . "\0" . 'codser');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Classe $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNumclas()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getNumclas();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumclas', array());

        return parent::getNumclas();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibclas($libclas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibclas', array($libclas));

        return parent::setLibclas($libclas);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibclas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibclas', array());

        return parent::getLibclas();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoefclas($coefclas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoefclas', array($coefclas));

        return parent::setCoefclas($coefclas);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoefclas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoefclas', array());

        return parent::getCoefclas();
    }

    /**
     * {@inheritDoc}
     */
    public function setJauge($jauge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJauge', array($jauge));

        return parent::setJauge($jauge);
    }

    /**
     * {@inheritDoc}
     */
    public function getJauge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJauge', array());

        return parent::getJauge();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodser(\DahouetBundle\Entity\Serie $codser = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodser', array($codser));

        return parent::setCodser($codser);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodser', array());

        return parent::getCodser();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumclas($numclas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumclas', array($numclas));

        return parent::setNumclas($numclas);
    }

}
