<?php

namespace Proxies\__CG__\DahouetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Participe extends \DahouetBundle\Entity\Participe implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'codepar', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'statut', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'dateinsc', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'tpsreel', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'codedec', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'place', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'tpscomp', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'heurarr', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'numport', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'numvoil', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'numreg', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'numlicski', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'numlic');
        }

        return array('__isInitialized__', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'codepar', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'statut', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'dateinsc', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'tpsreel', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'codedec', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'place', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'tpscomp', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'heurarr', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'numport', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'numvoil', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'numreg', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'numlicski', '' . "\0" . 'DahouetBundle\\Entity\\Participe' . "\0" . 'numlic');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Participe $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCodepar()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCodepar();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodepar', array());

        return parent::getCodepar();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut($statut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', array($statut));

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', array());

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateinsc($dateinsc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateinsc', array($dateinsc));

        return parent::setDateinsc($dateinsc);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateinsc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateinsc', array());

        return parent::getDateinsc();
    }

    /**
     * {@inheritDoc}
     */
    public function setTpsreel($tpsreel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTpsreel', array($tpsreel));

        return parent::setTpsreel($tpsreel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTpsreel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTpsreel', array());

        return parent::getTpsreel();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodedec($codedec)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodedec', array($codedec));

        return parent::setCodedec($codedec);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodedec()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodedec', array());

        return parent::getCodedec();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlace($place)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlace', array($place));

        return parent::setPlace($place);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlace', array());

        return parent::getPlace();
    }

    /**
     * {@inheritDoc}
     */
    public function setTpscomp($tpscomp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTpscomp', array($tpscomp));

        return parent::setTpscomp($tpscomp);
    }

    /**
     * {@inheritDoc}
     */
    public function getTpscomp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTpscomp', array());

        return parent::getTpscomp();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeurarr($heurarr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeurarr', array($heurarr));

        return parent::setHeurarr($heurarr);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeurarr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeurarr', array());

        return parent::getHeurarr();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumport($numport)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumport', array($numport));

        return parent::setNumport($numport);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumport()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumport', array());

        return parent::getNumport();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumvoil(\DahouetBundle\Entity\Voilier $numvoil = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumvoil', array($numvoil));

        return parent::setNumvoil($numvoil);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumvoil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumvoil', array());

        return parent::getNumvoil();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumreg(\DahouetBundle\Entity\Regate $numreg = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumreg', array($numreg));

        return parent::setNumreg($numreg);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumreg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumreg', array());

        return parent::getNumreg();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumlicski(\DahouetBundle\Entity\Licencie $numlicski = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumlicski', array($numlicski));

        return parent::setNumlicski($numlicski);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumlicski()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumlicski', array());

        return parent::getNumlicski();
    }

    /**
     * {@inheritDoc}
     */
    public function addNumlic(\DahouetBundle\Entity\Licencie $numlic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNumlic', array($numlic));

        return parent::addNumlic($numlic);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNumlic(\DahouetBundle\Entity\Licencie $numlic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNumlic', array($numlic));

        return parent::removeNumlic($numlic);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumlic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumlic', array());

        return parent::getNumlic();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodepar($codepar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodepar', array($codepar));

        return parent::setCodepar($codepar);
    }

}
