<?php

namespace Proxies\__CG__\DahouetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Licencie extends \DahouetBundle\Entity\Licencie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'DahouetBundle\\Entity\\Licencie' . "\0" . 'numlic', '' . "\0" . 'DahouetBundle\\Entity\\Licencie' . "\0" . 'nomlic', '' . "\0" . 'DahouetBundle\\Entity\\Licencie' . "\0" . 'ptsffv', '' . "\0" . 'DahouetBundle\\Entity\\Licencie' . "\0" . 'annlic', '' . "\0" . 'DahouetBundle\\Entity\\Licencie' . "\0" . 'datnaiss', '' . "\0" . 'DahouetBundle\\Entity\\Licencie' . "\0" . 'codepar');
        }

        return array('__isInitialized__', '' . "\0" . 'DahouetBundle\\Entity\\Licencie' . "\0" . 'numlic', '' . "\0" . 'DahouetBundle\\Entity\\Licencie' . "\0" . 'nomlic', '' . "\0" . 'DahouetBundle\\Entity\\Licencie' . "\0" . 'ptsffv', '' . "\0" . 'DahouetBundle\\Entity\\Licencie' . "\0" . 'annlic', '' . "\0" . 'DahouetBundle\\Entity\\Licencie' . "\0" . 'datnaiss', '' . "\0" . 'DahouetBundle\\Entity\\Licencie' . "\0" . 'codepar');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Licencie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNumlic()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getNumlic();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumlic', array());

        return parent::getNumlic();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomlic($nomlic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomlic', array($nomlic));

        return parent::setNomlic($nomlic);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomlic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomlic', array());

        return parent::getNomlic();
    }

    /**
     * {@inheritDoc}
     */
    public function setPtsffv($ptsffv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPtsffv', array($ptsffv));

        return parent::setPtsffv($ptsffv);
    }

    /**
     * {@inheritDoc}
     */
    public function getPtsffv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPtsffv', array());

        return parent::getPtsffv();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnlic($annlic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnlic', array($annlic));

        return parent::setAnnlic($annlic);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnlic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnlic', array());

        return parent::getAnnlic();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatnaiss($datnaiss)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatnaiss', array($datnaiss));

        return parent::setDatnaiss($datnaiss);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatnaiss()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatnaiss', array());

        return parent::getDatnaiss();
    }

    /**
     * {@inheritDoc}
     */
    public function addCodepar(\DahouetBundle\Entity\Participe $codepar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCodepar', array($codepar));

        return parent::addCodepar($codepar);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCodepar(\DahouetBundle\Entity\Participe $codepar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCodepar', array($codepar));

        return parent::removeCodepar($codepar);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodepar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodepar', array());

        return parent::getCodepar();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumlic($numlic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumlic', array($numlic));

        return parent::setNumlic($numlic);
    }

}
