<?php

namespace Proxies\__CG__\DahouetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Challenge extends \DahouetBundle\Entity\Challenge implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'DahouetBundle\\Entity\\Challenge' . "\0" . 'cdochal', '' . "\0" . 'DahouetBundle\\Entity\\Challenge' . "\0" . 'challenge', '' . "\0" . 'DahouetBundle\\Entity\\Challenge' . "\0" . 'datdebut', '' . "\0" . 'DahouetBundle\\Entity\\Challenge' . "\0" . 'datfin', '' . "\0" . 'DahouetBundle\\Entity\\Challenge' . "\0" . 'numvoil');
        }

        return array('__isInitialized__', '' . "\0" . 'DahouetBundle\\Entity\\Challenge' . "\0" . 'cdochal', '' . "\0" . 'DahouetBundle\\Entity\\Challenge' . "\0" . 'challenge', '' . "\0" . 'DahouetBundle\\Entity\\Challenge' . "\0" . 'datdebut', '' . "\0" . 'DahouetBundle\\Entity\\Challenge' . "\0" . 'datfin', '' . "\0" . 'DahouetBundle\\Entity\\Challenge' . "\0" . 'numvoil');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Challenge $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCdochal()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getCdochal();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCdochal', array());

        return parent::getCdochal();
    }

    /**
     * {@inheritDoc}
     */
    public function setChallenge($challenge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChallenge', array($challenge));

        return parent::setChallenge($challenge);
    }

    /**
     * {@inheritDoc}
     */
    public function getChallenge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChallenge', array());

        return parent::getChallenge();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatdebut($datdebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatdebut', array($datdebut));

        return parent::setDatdebut($datdebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatdebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatdebut', array());

        return parent::getDatdebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatfin($datfin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatfin', array($datfin));

        return parent::setDatfin($datfin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatfin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatfin', array());

        return parent::getDatfin();
    }

    /**
     * {@inheritDoc}
     */
    public function addNumvoil(\DahouetBundle\Entity\Voilier $numvoil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNumvoil', array($numvoil));

        return parent::addNumvoil($numvoil);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNumvoil(\DahouetBundle\Entity\Voilier $numvoil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNumvoil', array($numvoil));

        return parent::removeNumvoil($numvoil);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumvoil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumvoil', array());

        return parent::getNumvoil();
    }

    /**
     * {@inheritDoc}
     */
    public function setCdochal($cdochal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCdochal', array($cdochal));

        return parent::setCdochal($cdochal);
    }

}
